# Site settings
title: TEXT
header-img: img/home-bg.jpg
email: abc@gmail.com
description: "ABC"
baseurl: ""
url: ""
twitter_username: ABC
github_username:  ABC
facebook_username:  ABC

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","vendor"]
