# Site settings
title: Anomitra's Blog
header-img: img/home-bg.jpg
email: anomitra1993@gmail.com
description: "Just another weblog"
baseurl: "/"
url: "anomitra.me"
twitter_username: RickterScale_
github_username:  anomitra
facebook_username:  anomitra.saha

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","vendor"]
